import { type Game } from './types';

export const PLACEHOLDER_GAMES: Game[] = [
  {
    id: 'asteroid-dodge',
    title: 'Asteroid Dodge',
    description: 'Navigate your ship through an endless asteroid field. Fast reflexes required — one hit and you\'re space dust.',
    model: 'Claude Opus 4',
    thumbnail: '',
    tags: ['Arcade', 'Space', 'Survival'],
    rating: 4.7,
    playUrl: '#',
  },
  {
    id: 'pixel-kingdoms',
    title: 'Pixel Kingdoms',
    description: 'Build and defend your pixelated realm. Manage resources, train armies, and conquer neighboring territories.',
    model: 'GPT-4o',
    thumbnail: '',
    tags: ['Strategy', 'Pixel Art', 'Building'],
    rating: 4.3,
    playUrl: '#',
  },
  {
    id: 'neon-racer',
    title: 'Neon Racer',
    description: 'Blaze through procedurally generated neon circuits at breakneck speed. Synthwave soundtrack included.',
    model: 'Gemini 2.5 Pro',
    thumbnail: '',
    tags: ['Racing', 'Neon', 'Procedural'],
    rating: 4.5,
    playUrl: '#',
  },
  {
    id: 'word-wizard',
    title: 'Word Wizard',
    description: 'Cast spells by forming words from letter tiles. Longer words create more powerful magic attacks.',
    model: 'Claude Sonnet 4',
    thumbnail: '',
    tags: ['Puzzle', 'Word', 'RPG'],
    rating: 4.8,
    playUrl: '#',
  },
  {
    id: 'dungeon-descent',
    title: 'Dungeon Descent',
    description: 'A roguelike dungeon crawler with turn-based combat. Every run is different, every death is permanent.',
    model: 'DeepSeek R1',
    thumbnail: '',
    tags: ['Roguelike', 'Turn-based', 'Fantasy'],
    rating: 4.1,
    playUrl: '#',
  },
  {
    id: 'gravity-flip',
    title: 'Gravity Flip',
    description: 'Reverse gravity to navigate impossible platforming challenges. Simple controls, devious level design.',
    model: 'Llama 4 Scout',
    thumbnail: '',
    tags: ['Platformer', 'Physics', 'Puzzle'],
    rating: 4.6,
    playUrl: '#',
  },
  {
    id: 'color-collapse',
    title: 'Color Collapse',
    description: 'Match and collapse color clusters in this hypnotic chain-reaction puzzle game. Aim for the perfect clear.',
    model: 'GPT-4o',
    thumbnail: '',
    tags: ['Puzzle', 'Casual', 'Colors'],
    rating: 4.2,
    playUrl: '#',
  },
  {
    id: 'shadow-tactics',
    title: 'Shadow Tactics',
    description: 'Command a squad of stealth operatives in real-time tactical missions. Stay unseen or face the consequences.',
    model: 'Gemini 2.5 Pro',
    thumbnail: '',
    tags: ['Tactics', 'Stealth', 'Strategy'],
    rating: 4.4,
    playUrl: '#',
  },
];
